### PR TITLE
 Address `http-client-0.5.8` removal of `mMaxConns`.

### PR DESCRIPTION
**Pull request by naushadh**
Default to the static default-setting conn-count, since we can no longer find the manager's max conn-count or the settings its running with.

### CODE REVIEW

**Comment by axman6** [comment]
Hi @naushadh can you point me to some context for this change? I'm also confused about why the there's a need to use the `defaultManagerSettings` and not the manager that's actually in use?

**Comment by naushadh** [comment]
Hey @axman6, `amazonka-s3-streaming` HEAD uses the function `mMaxConns` from `http-client`'s `Network.HTTP.Client.Internal` module. However, as of Jan 16, `http-client-0.5.8` has dropped the function `mMaxConns` (a field of `Manager`). Also, `0.5.8`+ `Manager` does not expose its settings. So I thought the next best thing would be using the value from `defaultManagerSettings` to make `amazonka-s3-streaming` build again.

**Comment by axman6** [comment]
Hmm, interesting, and a bit of a shame they'd remove such useful functionality.

**Comment by axman6** [comment]
@naushadh Thanks for the PR, this has now been released as version 0.2.0.5

**Pull request merged**
